[soct-stage-xyz]
com_port = "COM5"
x_axis_travel = 150.0 # mm, https://www.pdvcn.com/motorized-xy-integral-combinating-stage/1197.html
y_axis_travel = 150.0 # mm
z_axis_travel = 60.0 # mm, https://www.pdvcn.com/motorized-lab-jack/electric-lifting-platform,-motorized-lab-jack,-elevator,-optical-sliding-lift-pt-gd401.html
homing_direction = 7 # XYZmask, int(0b111)
axis_direction = 0 # XYZmask, int(0b000)
x_axis_max_position = 80.0 # Adding 2 for the homing shift
y_axis_max_position = 82.0 # Adding 2 for the homing shift
z_axis_max_position = 30.5 # Adding 2 for the homing shift
position_objective = [22.5, 46.0]
position_vibratome = [74, 40]
position_afterCut = [74, 19]
position_maintenance = [0.0, 0.0, 0.0]
x_acceleration = 10.0 # mm/s^2
y_acceleration = 10.0 # mm/s^2
z_acceleration = 1.0 # mm/s^2
safe_move_margin = 2.5 # mm, margin to avoid hitting the sample holder and objective

[pli-stage-xyz]
com_port = "COM13"
x_axis_travel = 100.0 # mm
y_axis_travel = 100.0 # mm
z_axis_travel = 110.0 # mm
homing_direction = 7 # XYZmask, int(0b111) ZYX
axis_direction = 5 # XYZmask, int(0b101)
z_step_for_1mm = 340 # $102, number of z-steps to move 1 mm.


[pli-stage-rot]
com_port = "COM12"
top_rotation_travel = 335
bottom_rotation_travel = 180.0 # degrees
homing_direction = 3 #3,  XYZmask, int(0b011)
axis_direction = 3 #3,  XYZmask, int(0b011)

[vibratome]
serial_port = "USB0::0x0957::0x0407::MY44013298::INSTR"
cutting_frequency = 169  # Hz.
cutting_amplitude = 5.0 # V
min_frequency = 30 # HZ
max_frequency = 200 # Hz
feeding_rate = 1.0  # aka cutting speed, mm/s
cutting_distance = 30.0  # mm, in the negative y direction
slice_thickness = 0.2  # mm
maximum_cutting_height = 25.0 # mm, used to avoid damaging the sample holder and the stage. # TODO: calibrate this.
arduino_port = "COM6"
aurduino_control_pin = 2

[oct-camera]
server_path = "C:/Users/Joël/GitHub/linum-microscopes-soct/oct_server/build/Desktop_Qt_6_7_2_MSVC2019_64bit-Debug/debug/oct_server.exe"
server_address = "132.208.139.60"
server_port = "65432"
chunk_size = 1024
z_min = 150
z_max = 550
z_focus = 300
exposure_time_us = 23.0 # camera exposure time in microseconds
bscan_rate = 80 # B-scan rate in Hz (number of bscan per second)
maximum_scan_bandwidth = 175 # maximum galvo scan bandwidth in Hz for a sawtooth scan
tile_size = 750 # micron
tile_n_samples = 400 # number of samples per tile

[sbh] # Serial blockface histology (SBH) parameters
overlap_fraction = 0.2  # overlap fraction between 0.0 and 1.0
slice_thickness = 0.2  # mm
tile_wait_time = 0.0  # s
initial_search_size = 10.0 # mm
initial_search_fov_size = 1500 # micron
detection_margin = 0.5 # mm (margin around the detected mosaic ROI)